### ISSUE TITLE
Hi!

### ISSUE THREAD

**Issue by moehreag** [shizotoaster/TooltipTexture-Reforked#1]
Just wanted to provide some context as to why the mod was only published for quilt:
It was created after a discussion in Quilt's community with another member. That's it. We just didn't feel like trying to set up multi-loader buildscript jank again and it seemed like it wasn't needed (if you/someone else had asked for it that probably would've changed).
Anyway, if you have other questions or just want to chat just ask!

**Comment by shizotoaster** [comment]
Okay but why quilt.mod.json and no fabric.mod.json? The mod does not use any of quilt libraries, it doesn't even use fabric api. It's just a single mixin that works in fabric and quilt without any changes (unlike forge that require [some changes](https://github.com/shizotoaster/TooltipTexture-Reforked/blob/main/forge/src/main/java/net/shizotoaster/tooltiptexture/mixin/TooltipRenderUtilMixin.java)), so why restrict it to quilt?

**Comment by Yu-Vitaqua-fer-Chronos** [comment]
> Just wanted to provide some context as to why the mod was only published for quilt:
It was created after a discussion in Quilt's community with another member. __**That's it.**__

Seems pretty crystal on why she did what she did.
Also said if you asked, she coulda added support for both, so...

**Comment by moehreag** [comment]
> Okay but why quilt.mod.json and no fabric.mod.json? The mod does not use any of quilt libraries, it doesn't even use fabric api. It's just a single mixin that works in fabric and quilt without any changes (unlike forge that require [some changes](https://github.com/shizotoaster/TooltipTexture-Reforked/blob/main/forge/src/main/java/net/shizotoaster/tooltiptexture/mixin/TooltipRenderUtilMixin.java)), so why restrict it to quilt?

it was created in a quilt context. nothing else.

**Comment by shizotoaster** [comment]
Ok, no more questions. Added you to project members on modrinth, should've done that earlier
